# migration/generate_schema.py
"""
Reads the Access students table schema and generates a PostgreSQL
CREATE TABLE statement with council_id added.

Usage:
  python generate_schema.py --db "C:\path\to\database.accdb" --password 2600000
"""

import pyodbc
import argparse
import os

# Access -> PostgreSQL type mapping
TYPE_MAP = {
    "LONGCHAR":   "text",
    "VARCHAR":    "text",
    "CHAR":       "text",
    "INTEGER":    "integer",
    "SMALLINT":   "smallint",
    "REAL":       "numeric",
    "FLOAT":      "numeric",
    "DOUBLE":     "numeric",
    "CURRENCY":   "numeric(19,4)",
    "DATETIME":   "timestamptz",
    "DATE":       "date",
    "YESNO":      "boolean",
    "LONGBINARY": "bytea",
    "COUNTER":    "serial",
}

def access_type_to_pg(type_name: str) -> str:
    return TYPE_MAP.get(type_name.upper(), "text")

def get_table_schema(cursor, table_name: str) -> list:
    """Return list of (column_name, pg_type) tuples."""
    columns = []
    for row in cursor.columns(table=table_name):
        col_name = row.column_name
        type_name = row.type_name.split()[0].upper()
        pg_type = access_type_to_pg(type_name)
        columns.append((col_name, pg_type))
    return columns

def generate_create_table(table_name: str, columns: list) -> str:
    pg_table = table_name.lower().replace(" ", "_")
    lines = [f'CREATE TABLE IF NOT EXISTS "{pg_table}" (']
    lines.append('  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),')
    lines.append('  council_id   uuid NOT NULL REFERENCES councils(id),')
    for col_name, pg_type in columns:
        # Quote Hebrew column names
        lines.append(f'  "{col_name}"  {pg_type},')
    lines.append('  updated_at   timestamptz DEFAULT now()')
    lines.append(');')
    lines.append('')
    lines.append(f'ALTER TABLE "{pg_table}" ENABLE ROW LEVEL SECURITY;')
    lines.append(f'CREATE POLICY "council_isolation" ON "{pg_table}"')
    lines.append(f'  FOR SELECT USING (')
    lines.append(f'    council_id = (SELECT council_id FROM users WHERE id = auth.uid())')
    lines.append(f'  );')
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--db",       required=True, help="Path to .accdb file")
    parser.add_argument("--password", default="",    help="Database password")
    parser.add_argument("--table",    default=None,  help="Specific table (default: all)")
    args = parser.parse_args()

    conn_str = (
        f"DRIVER={{Microsoft Access Driver (*.mdb, *.accdb)}};"
        f"DBQ={args.db};"
        f"PWD={args.password};"
    )
    conn   = pyodbc.connect(conn_str)
    cursor = conn.cursor()

    # Get all user tables
    tables = [row.table_name for row in cursor.tables(tableType="TABLE")]
    if args.table:
        tables = [t for t in tables if t == args.table]

    output_lines = ["-- Generated by migration/generate_schema.py", "-- DO NOT EDIT MANUALLY", ""]
    for table in sorted(tables):
        print(f"Processing: {table}")
        cols = get_table_schema(cursor, table)
        output_lines.append(generate_create_table(table, cols))
        output_lines.append("")

    out_path = os.path.join(
        os.path.dirname(__file__),
        "..", "supabase", "migrations", "002_students_table.sql"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines))

    print(f"\nSchema written to: {out_path}")
    conn.close()

if __name__ == "__main__":
    main()
