-- supabase/migrations/003_excel_import_tables.sql
-- Two tables loaded monthly from Ministry of Education Excel exports.
-- All columns stored as text to avoid type-mismatch issues with raw ministry data.

-- ── Table 1: talmidim_kesher ─────────────────────────────────────
-- Source: *_Talmidim_gormey_kesher_pirtey_kesher_mosdot_megamot_kitot.xlsx
CREATE TABLE IF NOT EXISTS talmidim_kesher (
  id                              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  council_id                      uuid NOT NULL REFERENCES councils(id),
  "מזהה"                          text,
  "בישוב-מחוץ"                    text,
  "סמל מוטב"                      text,
  "שם מוטב"                       text,
  "סמל רשות חינוך"                text,
  "שם רשות חינוך"                 text,
  "שנת לימודים"                   text,
  "סמל מוסד"                      text,
  "שם מוסד"                       text,
  "סוג מסגרת"                     text,
  "ישוב מוסד"                     text,
  "כתובת מוסד"                    text,
  "טלפון מוסד"                    text,
  "גורם מדווח תאור"               text,
  "מגזר"                          text,
  "מעמד משפטי תאור"               text,
  "סוג פיקוח תאור"                text,
  "סוג חינוך תאור"                text,
  "שלבי חינוך מוסד"               text,
  "הרכב"                          text,
  "סוג זהות"                      text,
  "מספר זהות"                     bigint,
  "מספר דרכון"                    text,
  "קבוצת דרכון"                   text,
  "שם משפחה"                      text,
  "שם פרטי"                       text,
  "שם משפחה כינוי"                text,
  "שם פרטי כינוי"                 text,
  "מין"                           text,
  "לאום משרד הפנים"               text,
  "שם ארץ לידה"                   text,
  "שם ארץ עליה"                   text,
  "תאריך לידה"                    text,
  "תאריך עליה"                    text,
  "מספר אחים עד 18"               text,
  "שלב חינוך  תלמיד"              text,
  "שכבה"                          text,
  "מקבילה"                        text,
  "קוד סוג כיתה"                  text,
  "סוג כיתה"                      text,
  "סטטוס אישור כיתה"              text,
  "תאריך סטטוס אישור כיתה"        text,
  "מינימום תלמידים בכיתה"         text,
  "מקסימום תלמידים בכיתה"         text,
  "מסלול"                         text,
  "נתיב"                          text,
  "הסמכה"                         text,
  "סמל מגמה משרד"                 text,
  "תאור מגמה משרד"                text,
  "סמל מגמה מוסד"                 text,
  "תאור מגמה מוסד"                text,
  "מכסת תלמידים מבוקשת"           text,
  "סטטוס אישור מגמה"              text,
  "תאריך סטטוס אישור מגמה"        text,
  "מכסת תלמידים מאושרת למגמה"     text,
  "הערה סטטוס אישור מגמה"         text,
  "האם לשיבוץ תאור"               text,
  "תאור סטטוס רישום"              text,
  "תקינות שיבוץ"                  text,
  "תאריך תחילת שיבוץ"             text,
  "תאריך סיום שיבוץ"              text,
  "סיבת עזיבה"                    text,
  "פירוט עזיבה"                   text,
  "קוד סוג שגיאת דווח"            text,
  "תאור סוג שגיאת דווח"           text,
  "קוד זכאות לשכר לימוד"          text,
  "תאור זכאות לשכר לימוד"         text,
  "תאריך חזרה מחול"               text,
  "שנות לימוד בחול"               text,
  "לא לדווח מצבת"                 text,
  "מספר זהות קודם"                text,
  "סוג זהות קודמת"                text,
  "תאריך עדכון מקסימלי"           text,
  "האם רשות אחרת תאור"            text,
  "סמל רשות מגורים תלמיד"         text,
  "שם רשות מגורים תלמיד"          text,
  "סמל ישוב 1ת"                   text,
  "תאור ישוב 1ת"                  text,
  "שם רחוב 1ת"                    text,
  "מספר בית 1ת"                   text,
  "מספר דירה 1ת"                  text,
  "סמל ישוב 2ת"                   text,
  "תאור ישוב 2ת"                  text,
  "שם רחוב 2ת"                    text,
  "מספר בית 2ת"                   text,
  "כניסה 2ת"                      text,
  "מספר דירה 2ת"                  text,
  "תא דואר 2ת"                    text,
  "מיקוד 2ת"                      text,
  "שכונה 2ת"                      text,
  "הערה 2ת"                       text,
  "דואר נע 2ת"                    text,
  "מספר נייח 1ת"                  text,
  "מספר נייח 2ת"                  text,
  "מספר נייד 1ת"                  text,
  "מספר נייד 2ת"                  text,
  "מייל ת"                        text,
  "סטטוס הצהרת מנהל1"             text,
  "סוג זהות גורם קשר1"            text,
  "מספר זהות גורם קשר1"           text,
  "סוג קירבה תאור1"               text,
  "שם מלא1"                       text,
  "האם לקבל מידע1"                text,
  "האם משלם1"                     text,
  "תאור מעמד הורה1"               text,
  "האם פרטי קשר תלמיד1"           text,
  "נייח 1 1"                      text,
  "נייח 2 1"                      text,
  "נייד 1 1"                      text,
  "נייד 2 1"                      text,
  "ישוב מרשם1"                    text,
  "רחוב מרשם1"                    text,
  "מספר בית מרשם1"                text,
  "מספר דירה מרשם1"               text,
  "מיקוד מרשם1"                   text,
  "ישוב1"                         text,
  "שכונה1"                        text,
  "רחוב1"                         text,
  "מספר בית1"                     text,
  "מספר דירה1"                    text,
  "מיקוד1"                        text,
  "כניסה1"                        text,
  "תא דואר1"                      text,
  "הערה1"                         text,
  "דואר נע1"                      text,
  "מספר נייד 2 1"                 text,
  "מייל 1"                        text,
  "סטטוס הצהרת מנהל2"             text,
  "סוג זהות גורם קשר2"            text,
  "מספר זהות גורם קשר2"           text,
  "סוג קרבה תאור 2"               text,
  "שם מלא2"                       text,
  "האם לקבל מידע2"                text,
  "האם משלם 2"                    text,
  "תאור מעמד הורה2"               text,
  "האם פרטי קשר תלמיד2"           text,
  "נייח 1 2"                      text,
  "נייח 2 2"                      text,
  "נייד 1 2"                      text,
  "נייד 2 2"                      text,
  "ישוב מרשם2"                    text,
  "רחוב מרשם2"                    text,
  "מספר בית מרשם2"                text,
  "מספר דירה מרשם2"               text,
  "מיקוד מרשם2"                   text,
  "ישוב2"                         text,
  "שכונה2"                        text,
  "רחוב2"                         text,
  "מספר בית2"                     text,
  "מספר דירה2"                    text,
  "מיקוד2"                        text,
  "כניסה2"                        text,
  "תא דואר2"                      text,
  "הערה2"                         text,
  "דואר נע2"                      text,
  "מספר נייד 2 2"                 text,
  "מייל 2"                        text,
  updated_at                      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS talmidim_kesher_council_id_idx ON talmidim_kesher(council_id);
CREATE INDEX IF NOT EXISTS talmidim_kesher_mispar_zehut_idx ON talmidim_kesher("מספר זהות");

ALTER TABLE talmidim_kesher ENABLE ROW LEVEL SECURITY;
CREATE POLICY "council_isolation_kesher" ON talmidim_kesher
  FOR SELECT USING (
    council_id = (SELECT council_id FROM users WHERE id = auth.uid())
  );


-- ── Table 2: talmidim_nospim ─────────────────────────────────────
-- Source: *_additional_fields_filled.xlsx
CREATE TABLE IF NOT EXISTS talmidim_nospim (
  id                                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  council_id                                uuid NOT NULL REFERENCES councils(id),
  "מזהה"                                    text,
  "מספר זהות תוספתי"                        bigint,
  "חינוך מיוחד תלמיד"                      text,
  "חינוך מיוחד אפיון וזכאות"               text,
  "חינוך מיוחד משבצת"                      text,
  "חינוך מיוחד סלים אישיים"                text,
  "חינוך מיוחד לפי מוסד או כיתה"           text,
  "סל זכאות בכיתה רגילה"                   text,
  "זכאי שעות סייעת"                         text,
  "מספר שעות זכאות סייעת"                  text,
  "במשבצת"                                  text,
  "תלמיד חוץ"                              text,
  "תלמיד תושב"                              text,
  "תלמיד תושב לומד בחוץ"                   text,
  "תלמיד במוסד ברשות"                      text,
  "לא במרשם אוכלוסין"                       text,
  "הערות"                                   text,
  "שכבה וכיתה בפועל"                        text,
  "מגבלה רפואית"                            text,
  "קופת חולים תלמיד"                        text,
  "הערה"                                    text,
  "אגרת חוץ"                               text,
  "לידה עד 3"                               text,
  "גן חובה 4-6"                             text,
  "גיל ב""ס א-י""ד"                         text,
  "קידום נוער"                              text,
  "תלמידי תמת"                              text,
  "חינוך ביתי"                              text,
  "מטופלי קב""ס"                            text,
  "כיתת חרוב"                              text,
  "קבצים מצורפים"                           text,
  "סטטוס היל""ה"                            text,
  "מפונים לבירור"                           text,
  "מפונים מאושרים"                          text,
  "בעיית ישוב מגורים לבירור"               text,
  "זכאי סל תלמיד רשותי"                    text,
  "פוטנציאל לרישום מכוח המיפוי"            text,
  "זכאי הסעה ח""מ"                          text,
  "זכאי ליווי בהסעה"                        text,
  "זכאי הסעה קפיטה-ברשות"                  text,
  "זכאי הסעה קפיטה-מיפוי ערבי"             text,
  "זכאי הסעה קפיטה-מיפוי יהודי"            text,
  updated_at                                timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS talmidim_nospim_council_id_idx ON talmidim_nospim(council_id);
CREATE INDEX IF NOT EXISTS talmidim_nospim_mispar_zehut_idx ON talmidim_nospim("מספר זהות תוספתי");

ALTER TABLE talmidim_nospim ENABLE ROW LEVEL SECURITY;
CREATE POLICY "council_isolation_nospim" ON talmidim_nospim
  FOR SELECT USING (
    council_id = (SELECT council_id FROM users WHERE id = auth.uid())
  );
