-- supabase/migrations/004_general_tables.sql

-- Source: 7 ישובי המועצה האזורית
CREATE TABLE IF NOT EXISTS yishuvei_hamoatza (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  council_id  uuid NOT NULL REFERENCES councils(id),
  "סמל ישוב"  integer,
  "TEUR_YISHUV"  text,
  "סימון ישוב"  text,
  "סוציואקונומי ישוב"  text,
  "אוכלוסיה בישוב"  integer,
  "סמל ישוב ישן"  integer,
  "מועצה אזורית"  text,
  "סוציואקונומי מועצה"  integer,
  "אוכלוסיה מועצה"  integer,
  "מספר תלמידים בישוב"  integer,
  "סה""כ תלמידים בישוב"  integer,
  "שדה3"  text,
  updated_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS yishuvei_hamoatza_council_idx ON yishuvei_hamoatza(council_id);
ALTER TABLE yishuvei_hamoatza ENABLE ROW LEVEL SECURITY;
CREATE POLICY "council_isolation_yishuvei_hamoatza" ON yishuvei_hamoatza
  FOR SELECT USING (council_id = (SELECT council_id FROM users WHERE id = auth.uid()));

-- Source: 9997סמל ישוב ורחובות
CREATE TABLE IF NOT EXISTS semel_yishuv_verechevot (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "מזהה"  bigint,
  "סמל ישוב רחובות"  integer,
  "שם ישוב"  text,
  "סמל רחוב"  integer,
  "שם רחוב"  text,
  "סמל ישוב חינוך"  text,
  "שם רשות מקומית"  text,
  "סוג רשות מקומית"  text,
  updated_at  timestamptz DEFAULT now()
);

ALTER TABLE semel_yishuv_verechevot ENABLE ROW LEVEL SECURITY;
CREATE POLICY "open_read_semel_yishuv_verechevot" ON semel_yishuv_verechevot
  FOR SELECT USING (auth.role() = 'authenticated');

-- Source: 9998 טבלה להמרת סמלי ישוב קצרים בארוכים
CREATE TABLE IF NOT EXISTS hamarat_semelei_yishuv (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  council_id  uuid NOT NULL REFERENCES councils(id),
  "מזהה"  bigint,
  "תז תלמיד"  integer,
  "סמל ישוב"  integer,
  "שם ישוב"  text,
  updated_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS hamarat_semelei_yishuv_council_idx ON hamarat_semelei_yishuv(council_id);
ALTER TABLE hamarat_semelei_yishuv ENABLE ROW LEVEL SECURITY;
CREATE POLICY "council_isolation_hamarat_semelei_yishuv" ON hamarat_semelei_yishuv
  FOR SELECT USING (council_id = (SELECT council_id FROM users WHERE id = auth.uid()));

-- Source: 9998 סמל ישוב - 140 TABLE
CREATE TABLE IF NOT EXISTS semel_yishuv_140 (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "סמל ישוב"  integer,
  "תאור ישוב"  text,
  "סימון ישוב"  text,
  "סוציואקונומי ישוב"  text,
  "אוכלוסיה בישוב"  integer,
  "סמל ישוב קצר-רחובות"  integer,
  "מועצה אזורית"  text,
  "סוציואקונומי מועצה"  integer,
  "אוכלוסיה מועצה"  integer,
  "שדה1"  text,
  "שדה2"  text,
  "שדה3"  text,
  "שדה4"  text,
  "שדה5"  text,
  "שדה6"  text,
  "שדה7"  text,
  "שדה8"  text,
  "שדה9"  text,
  "שדה10"  text,
  "שדה11"  text,
  "שדה12"  text,
  "שדה13"  numeric,
  "שדה14"  text,
  "שדה15"  text,
  "שדה16"  text,
  "שדה17"  text,
  "שדה18"  text,
  "שדה19"  text,
  "שדה20"  text,
  "שדה21"  text,
  "שדה22"  text,
  "שדה23"  text,
  "שדה24"  timestamptz,
  "שדה25"  text,
  "שדה26"  text,
  "שדה27"  text,
  "שדה28"  text,
  "שדה29"  numeric,
  "שדה30"  text,
  "שדה31"  text,
  "שדה32"  text,
  "שדה33"  text,
  "שדה34"  text,
  "שדה35"  text,
  "שדה36"  text,
  "שדה37"  text,
  "שדה38"  text,
  "שדה39"  text,
  "שדה40"  text,
  "שדה41"  text,
  "שדה42"  text,
  "שדה43"  text,
  "שדה44"  text,
  "שדה45"  text,
  "שדה46"  text,
  "שדה47"  text,
  "שדה48"  text,
  "שדה49"  text,
  "שדה50"  text,
  "שדה51"  text,
  "שדה52"  text,
  "שדה53"  text,
  "שדה54"  text,
  "שדה55"  text,
  "שדה56"  text,
  "שדה57"  text,
  "שדה58"  text,
  "שדה59"  text,
  "שדה60"  text,
  "שדה61"  text,
  "שדה62"  text,
  "שדה63"  text,
  "שדה64"  text,
  "שדה65"  text,
  "שדה66"  text,
  "שדה67"  text,
  "שדה68"  numeric,
  "שדה69"  text,
  "שדה70"  text,
  "שדה71"  text,
  "שדה72"  text,
  "שדה73"  text,
  "שדה74"  text,
  "שדה75"  text,
  "שדה76"  text,
  "שדה77"  text,
  "שדה78"  text,
  "שדה79"  text,
  "שדה80"  text,
  "שדה81"  text,
  "שדה82"  text,
  "שדה83"  text,
  "שדה84"  text,
  "שדה85"  text,
  "שדה86"  text,
  "שדה87"  text,
  "שדה88"  text,
  "שדה89"  text,
  "שדה90"  text,
  "שדה91"  numeric,
  "שדה92"  text,
  "שדה93"  text,
  "שדה94"  text,
  "שדה95"  text,
  "שדה96"  text,
  "שדה97"  text,
  "שדה98"  text,
  "שדה99"  text,
  "שדה100"  text,
  "שדה101"  text,
  "שדה102"  text,
  "שדה103"  text,
  "שדה104"  text,
  "שדה105"  text,
  "שדה106"  text,
  "שדה107"  text,
  "שדה108"  text,
  "שדה109"  text,
  "שדה110"  text,
  "שדה111"  text,
  "שדה112"  text,
  "שדה113"  text,
  "שדה114"  text,
  "שדה115"  text,
  "שדה116"  text,
  "שדה117"  text,
  "שדה118"  text,
  "שדה119"  text,
  "שדה120"  text,
  "שדה121"  numeric,
  "שדה122"  text,
  "שדה123"  text,
  "שדה124"  text,
  "שדה125"  text,
  "שדה126"  text,
  "שדה127"  text,
  "שדה128"  text,
  "שדה129"  text,
  "שדה130"  text,
  "שדה131"  text,
  "שדה132"  text,
  "שדה133"  text,
  "שדה134"  text,
  "שדה135"  text,
  "שדה136"  text,
  "שדה137"  text,
  "שדה138"  text,
  "שדה139"  text,
  "שדה140"  text,
  "שדה141"  text,
  "שדה142"  text,
  "שדה143"  text,
  "שדה144"  text,
  "שדה145"  text,
  "שדה146"  text,
  "שדה147"  text,
  "שדה148"  text,
  "שדה149"  text,
  "שדה150"  text,
  "שדה151"  text,
  "שדה152"  text,
  "שדה153"  text,
  "שדה154"  text,
  "שדה155"  text,
  "שדה156"  text,
  "שדה157"  text,
  "שדה158"  text,
  "שדה159"  text,
  updated_at  timestamptz DEFAULT now()
);

ALTER TABLE semel_yishuv_140 ENABLE ROW LEVEL SECURITY;
CREATE POLICY "open_read_semel_yishuv_140" ON semel_yishuv_140
  FOR SELECT USING (auth.role() = 'authenticated');

-- Source: 9999 - מוסדות חינוך 2024
CREATE TABLE IF NOT EXISTS mosdot_chinuch (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "סמל מוסד"  numeric,
  "שם מוסד"  text,
  "יישוב מוסד"  text,
  "יישוב למכתבים"  text,
  "כתובת"  text,
  "כתובת חט""ב"  text,
  "רשות חינוך"  text,
  "שם מנהל"  text,
  "שם ממונה חט""ב"  text,
  "כתובת למכתבים"  text,
  "כתובת למכתבים חט""ב"  text,
  "מפקח\מדריך"  text,
  "טלפון"  text,
  "פקס"  text,
  "דוא""ל מזכירות"  text,
  "מיקוד"  numeric,
  "שלב חינוך מוסדות"  text,
  "קוד שלב חינוך"  numeric,
  "סוג חינוך מוסדות"  text,
  "קוד סוג חינוך"  numeric,
  "מעמד משפטי"  text,
  "קוד מעמד משפטי"  numeric,
  "סוג פיקוח מוסדות"  text,
  "קוד סוג פיקוח"  numeric,
  "מגזר 2"  text,
  "קוד מגזר"  numeric,
  "יחידת דיווח"  text,
  "קוד יחידת דיווח"  numeric,
  "בעלות"  text,
  "קוד בעלות"  numeric,
  "יוח""א"  text,
  "אופק חדש"  text,
  "תאריך הצטרפות לאופק חדש"  text,
  "טווח שכבות מוסד"  text,
  "שנת ייסוד"  numeric,
  "שפת לימוד"  text,
  "מספר תלמידים"  numeric,
  "סטאטוס בעוז לתמורה"  text,
  "תאריך הצטרפות לעוז לתמורה"  text,
  "סוג מוסד"  text,
  "משוייך לרשות המקומית"  text,
  "סמל מוסד לפעולות"  numeric,
  "סוג פיקוח תוספתי"  text,
  "תאגיד"  text,
  updated_at  timestamptz DEFAULT now()
);

ALTER TABLE mosdot_chinuch ENABLE ROW LEVEL SECURITY;
CREATE POLICY "open_read_mosdot_chinuch" ON mosdot_chinuch
  FOR SELECT USING (auth.role() = 'authenticated');
